// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    C_AreaCascade: typeof import('./src/components/C_AreaCascade/index.vue')['default']
    C_BaseIcon: typeof import('./src/components/C_BaseIcon/index.vue')['default']
    C_Calendar: typeof import('./src/components/C_Calendar/index.vue')['default']
    C_City: typeof import('./src/components/C_City/index.vue')['default']
    C_CityFilterable: typeof import('./src/components/C_CityFilterable/index.vue')['default']
    C_CityView: typeof import('./src/components/C_CityView/index.vue')['default']
    C_Container: typeof import('./src/components/C_Container/index.vue')['default']
    C_Date: typeof import('./src/components/C_Date/index.vue')['default']
    C_Form: typeof import('./src/components/C_Form/index.vue')['default']
    C_FormModal: typeof import('./src/components/C_FormModal/index.vue')['default']
    C_Icon: typeof import('./src/components/C_Icon/index.vue')['default']
    C_List: typeof import('./src/components/C_List/index.vue')['default']
    C_Menu: typeof import('./src/components/C_Menu/index.vue')['default']
    C_NavHeader: typeof import('./src/components/C_NavHeader/index.vue')['default']
    C_NavSide: typeof import('./src/components/C_NavSide/index.vue')['default']
    C_Notice: typeof import('./src/components/C_Notice/index.vue')['default']
    C_Progress: typeof import('./src/components/C_Progress/index.vue')['default']
    C_Table: typeof import('./src/components/C_Table/index.vue')['default']
    C_Time: typeof import('./src/components/C_Time/index.vue')['default']
    C_Trend: typeof import('./src/components/C_Trend/index.vue')['default']
  }
}

export { }
