/*
 * @Author: ChenYu
 * @Date: 2022-04-28 10:35:52
 * @LastEditors: ChenYu
 * @LastEditTime: 2022-05-06 09:04:41
 * @FilePath: \v3-el-components\src\views\menu-manage\data.tsx
 * @Description:
 * Copyright (c) ${2022} by ChenYu/天智AgileTeam, All Rights Reserved.
 */

import { t } from '_utils/d_i18n'
import { I_FormOptions } from '_c/C_Form/types/types'
import { v_required } from '_utils/v_verify'

export const treeData = [
  {
    alwaysShow: true,
    cache: null,
    checked: false,
    children: [
      {
        cache: null,
        checked: false,
        children: [
          {
            alwaysShow: false,
            cache: null, // 是否需要缓存
            checked: false, // 是否点击选中
            children: [],
            code: 'profile', // 对应路由信息中的name
            expand: true, // 是否默认展开
            hasAccess: null,
            herf: '',
            hidden: false, // 是否需要隐藏
            httpMethod: '',
            icon: 'icongouwurili',
            id: '884387908448178176',
            menuDesc: '',
            menuId: '884387908448178176',
            menuStatus: false,
            orderNum: 0, // 排序使用
            parentId: '884385325578997760',
            path: '/profile',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '个人中心',
            label: '个人中心',
            type: 0,
          },
        ],
        code: 'home',
        expand: true,
        herf: '',
        hidden: false,
        httpMethod: '',
        icon: 'HomeFilled',
        id: '884385008191819769',
        label: '首页',
        menuDesc: '',
        menuId: '884385008191819769',
        menuStatus: false,
        orderNum: 0,
        parentId: '1',
        path: '/home',
        redirect: '',
        route: false,
        systemCode: 0,
        title: '首页',
        type: 0,
      },
      {
        cache: null,
        checked: false,
        children: [
          {
            cache: null,
            checked: false,
            children: [],
            code: 'base_icon',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '884387908448178176',
            menuDesc: '',
            menuId: '884387908448178176',
            menuStatus: false,
            orderNum: 0,
            parentId: '884385325578997760',
            path: '/base_icon',
            route: false,
            systemCode: 0,
            title: '图标选择器',
            label: '图标选择器',
            type: 0,
          },
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [],
            code: 'area_cascade',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '884398620469907456',
            label: '级联选择器',
            menuDesc: '',
            menuId: '884398620469907456',
            menuStatus: false,
            orderNum: 0,
            parentId: '884385325578997760',
            path: '/area_cascade',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '级联选择器',
            type: 0,
          },
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [],
            code: 'notice',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '915572047015317504',
            label: '通知列表',
            menuDesc: '',
            menuId: '915572047015317504',
            menuStatus: false,
            orderNum: 0,
            parentId: '884385325578997760',
            path: '/notice',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '通知列表',
            type: 0,
          },
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [],
            code: 'menu',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '915572199591514112',
            label: '菜单',
            menuDesc: '',
            menuId: '915572199591514112',
            menuStatus: false,
            orderNum: 0,
            parentId: '884385325578997760',
            path: '/menu',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '菜单',
            type: 0,
          },
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [],
            code: 'progress',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '884401111093760000',
            label: '进度条',
            menuDesc: '',
            menuId: '884401111093760000',
            menuStatus: false,
            orderNum: 0,
            parentId: '884385325578997763',
            path: '/progress',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '进度条',
            type: 0,
          },
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [],
            code: 'time',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '915572199591514112',
            label: '时间选择器',
            menuDesc: '',
            menuId: '915572199591514112',
            menuStatus: false,
            orderNum: 0,
            parentId: '884385325578997760',
            path: '/time',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '时间选择器',
            type: 0,
          },
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [],
            code: 'date',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '884400252565868544',
            label: '日期选择器',
            menuDesc: '',
            menuId: '884400252565868544',
            menuStatus: false,
            orderNum: 0,
            parentId: '884385325578997762',
            path: '/date',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '日期选择器',
            type: 0,
          },
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [],
            code: 'city',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '884400163436908544',
            label: '城市选择器',
            menuDesc: '',
            menuId: '884400163436908544',
            menuStatus: false,
            orderNum: 0,
            parentId: '884385325578997762',
            path: '/city',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '城市选择器',
            type: 0,
          },
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [
              {
                alwaysShow: false,
                cache: null,
                checked: false,
                children: [],
                code: 'form',
                expand: true,
                hasAccess: null,
                herf: '',
                hidden: false,
                httpMethod: '',
                icon: 'default',
                id: '884399411444338688',
                label: '表单',
                menuDesc: '',
                menuId: '884399411444338688',
                menuStatus: false,
                orderNum: 0,
                parentId: '884385325578997761',
                path: '/form',
                redirect: '',
                route: false,
                systemCode: 0,
                title: '表单',
                type: 0,
              },
              {
                alwaysShow: false,
                cache: null,
                checked: false,
                children: [],
                code: 'form-modal',
                expand: true,
                hasAccess: null,
                herf: '',
                hidden: false,
                httpMethod: '',
                icon: 'default',
                id: '884400345855578112',
                label: '模态框表单',
                menuDesc: '',
                menuId: '884400345855578112',
                menuStatus: false,
                orderNum: 0,
                parentId: '884385325578997762',
                path: '/form-modal',
                redirect: '',
                route: false,
                systemCode: 0,
                title: '模态框表单',
                type: 0,
              },
            ],
            code: 'form_manage',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '955523149062606848',
            label: '表单模块',
            menuDesc: '',
            menuId: '955523149062606848',
            menuStatus: false,
            orderNum: 0,
            parentId: '884385325578997761',
            path: '/form-manage',
            redirect: '/form',
            route: false,
            systemCode: 0,
            title: '表单模块',
            type: 0,
          },
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [],
            code: 'table',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '884400874308521984',
            label: '表格',
            menuDesc: '',
            menuId: '884400874308521984',
            menuStatus: false,
            orderNum: 0,
            parentId: '884385325578997762',
            path: '/table',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '表格',
            type: 0,
          },
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [],
            code: 'calendar',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'iconshenhezhongxin1',
            id: '884385325578997763',
            label: '日历',
            menuDesc: '',
            menuId: '884385325578997763',
            menuStatus: false,
            orderNum: 0,
            parentId: '1',
            path: '/calendar',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '日历',
            type: 0,
          },
        ],
        code: 'demo',
        expand: true,
        herf: '',
        hidden: false,
        httpMethod: '',
        icon: 'Help',
        id: '884385325578997760',
        menuDesc: '',
        menuId: '884385325578997760',
        menuStatus: false,
        orderNum: 0,
        parentId: '1',
        path: '/demo',
        redirect: '/base_icon',
        route: false,
        systemCode: 0,
        title: '示范组件',
        label: '示范组件',
        type: 0,
      },

      {
        alwaysShow: false,
        cache: null,
        checked: false,
        children: [
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [],
            code: 'user-manage',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '884399341990858752',
            label: '用户管理',
            menuDesc: '',
            menuId: '884399341990858752',
            menuStatus: false,
            orderNum: 0,
            parentId: '884385325578997761',
            path: '/user-manage',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '用户管理',
            type: 0,
          },
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [],
            code: 'roleList',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '884400967287853056',
            label: '角色列表',
            menuDesc: '',
            menuId: '884400967287853056',
            menuStatus: false,
            orderNum: 0,
            parentId: '884385325578997762',
            path: '/roleList',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '角色列表',
            type: 0,
          },
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [],
            code: 'permissionList',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '884401030034640896',
            label: '权限列表',
            menuDesc: '',
            menuId: '884401030034640896',
            menuStatus: false,
            orderNum: 0,
            parentId: '884385325578997762',
            path: '/permissionList',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '权限列表',
            type: 0,
          },
        ],
        code: 'user',
        expand: true,
        hasAccess: null,
        herf: '',
        hidden: false,
        httpMethod: '',
        icon: 'User',
        id: '884385325578997761',
        label: '用户中心',
        menuDesc: '',
        menuId: '884385325578997761',
        menuStatus: false,
        orderNum: 0,
        parentId: '1',
        path: '/user',
        redirect: '',
        route: false,
        systemCode: 0,
        title: '用户中心',
        type: 0,
      },

      {
        alwaysShow: false,
        cache: null,
        checked: false,
        children: [
          {
            alwaysShow: false,
            cache: null,
            checked: false,
            children: [],
            code: 'menu_manage',
            expand: true,
            hasAccess: null,
            herf: '',
            hidden: false,
            httpMethod: '',
            icon: 'default',
            id: '928237917267431424',
            label: '菜单管理',
            menuDesc: '',
            menuId: '928237917267431424',
            menuStatus: false,
            orderNum: 0,
            parentId: '928237672693370880',
            path: '/menu_manage',
            redirect: '',
            route: false,
            systemCode: 0,
            title: '菜单管理',
            type: 0,
          },
        ],
        code: 'sys_manage',
        expand: true,
        hasAccess: null,
        herf: '',
        hidden: false,
        httpMethod: '',
        icon: 'Tools',
        id: '884385325578997762',
        label: '系统管理',
        menuDesc: '',
        menuId: '884385325578997762',
        menuStatus: false,
        orderNum: 0,
        parentId: '1',
        path: '/sys_manage',
        redirect: '',
        route: false,
        systemCode: 0,
        title: '系统管理',
        type: 0,
      },
    ],
    code: 'root',
    component: 'root',
    expand: true,
    hasAccess: null,
    herf: "''",
    hidden: true,
    httpMethod: "''",
    icon: 'Menu',
    id: '1',
    label: '系统菜单',
    menuDesc: '系统菜单',
    menuId: '1',
    menuStatus: false,
    orderNum: 1,
    parentId: '-1',
    path: '‘’',
    redirect: 'root',
    route: true,
    systemCode: 0,
    title: '系统菜单',
    type: 0,
  },
]

// TODO: 要渲染的列表项
export const COLUMNS = (
  tableData: any,
  visible: Ref<boolean>,
  selectRoleId: string,
  editResources: any
): I_TableColumns[] => {
  return [
    {
      type: 'index',
      label: '序号',
      width: 60,
    },
    {
      label: '编码',
      prop: 'code',
    },
    {
      label: '类型',
      prop: 'type',
    },
    {
      label: '名称',
      prop: 'title',
    },
    {
      label: '接口地址',
      prop: 'herf',
    },
    {
      label: '请求类型',
      prop: 'httpMethod',
    },
    {
      label: t('role.action'),
      render: ({ row }) => (
        <>
          <el-button
            size="small"
            type="warning"
            onClick={() => editResources()}
          >
            <el-icon-edit />
          </el-button>
          <el-button size="small" type="danger">
            <el-icon-delete />
          </el-button>
        </>
      ),
    },
  ]
}

export const OPTIONS: I_FormOptions[] = [
  {
    type: 'input',
    value: '',
    label: '路径',
    prop: 'path',
    placeholder: '请输入路由path',
    rules: v_required('路径不能为空'),
    attrs: {
      clearable: true,
    },
  },
  {
    type: 'input',
    value: '',
    label: '编码',
    prop: 'code',
    placeholder: '请输入路由name',
    rules: v_required('编码不能为空'),
    attrs: {
      clearable: true,
    },
  },
  {
    type: 'input',
    value: '',
    label: '名称',
    prop: 'title',
    placeholder: '请输入路由meta.title',
    rules: v_required('名称不能为空'),
    attrs: {
      clearable: true,
    },
  },
  {
    type: 'input',
    value: '',
    label: '组件',
    prop: 'username',
    placeholder: '请输入路由component',
    rules: v_required('组件不能为空'),
    attrs: {
      clearable: true,
    },
  },
  {
    type: 'input',
    value: '',
    label: '图标',
    prop: 'icon',
    placeholder: '请输入路由meta.icon',
    attrs: {
      clearable: true,
    },
  },
  {
    type: 'switch',
    value: false,
    prop: 'hidden',
    label: '是否隐藏',
    attrs: {
      activeText: '是',
      inactiveText: '否',
      inlinePrompt: true,
    },
  },
  {
    type: 'switch',
    value: false,
    prop: 'cache',
    label: '是否缓存',
    attrs: {
      activeText: '是',
      inactiveText: '否',
      inlinePrompt: true,
    },
  },
]
